### ISSUE TITLE
[question] Attiny84 vs Attiny85

### ISSUE THREAD

**Issue by sredni** [irukard/NAM-I2C-RGB-LED-BAR#2]
Is there any particular reason to use Attiny84 in favor of Attiny85? We need to use only one pin to handle WS2812B, so smaller one should be better choice - less power, less space on pcb.

**Comment by irukard** [comment]
Attiny84 is cheaper. Can operate with slightly wider range of voltages. We know it quite good from tinyBrd project. Also we made prototype using tinyBrd 2.0, so there was no reason to migrate to Attiny85.

**Comment by sredni** [comment]
Thanks for information! I've got both Attiny85 and Attiny84 and it is more convenient for me to use Attiny85. So to sum this up: there is no reason to not to use Attiny85?
